name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17, 21]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
            
    - name: Generate JaCoCo Test Report
      run: ./gradlew jacocoTestReport
      
    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report-${{ matrix.java-version }}
        path: build/reports/jacoco/
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.java-version }}
        path: build/reports/tests/
        
    - name: Upload Checkstyle results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: checkstyle-results-${{ matrix.java-version }}
        path: build/reports/checkstyle/
        
    - name: Upload PMD results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pmd-results-${{ matrix.java-version }}
        path: build/reports/pmd/